# Generated by Django 5.2.5 on 2025-09-15 14:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketanalysis", "0002_alter_housingdata_uploaded_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MLSNumber", models.CharField(blank=True, max_length=100, null=True)),
                ("StreetNumberNumeric", models.IntegerField(blank=True, null=True)),
                ("StreetName", models.CharField(blank=True, max_length=255, null=True)),
                ("City", models.CharField(blank=True, max_length=120, null=True)),
                ("CDOM", models.IntegerField(blank=True, null=True)),
                ("ListPrice", models.FloatField(blank=True, null=True)),
                ("CurrentPrice", models.FloatField(blank=True, null=True)),
                ("ClosePrice", models.FloatField(blank=True, null=True)),
                ("PendingDate", models.DateField(blank=True, null=True)),
                ("CloseDate", models.DateField(blank=True, null=True)),
                ("SqFtTotal", models.FloatField(blank=True, null=True)),
                ("SqFtLivArea", models.FloatField(blank=True, null=True)),
                ("View", models.CharField(blank=True, max_length=120, null=True)),
                ("WaterView", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="uploads/")),
                ("save_sales_to_db", models.BooleanField(default=False)),
                ("rows_processed", models.IntegerField(default=0)),
                ("rows_excluded", models.IntegerField(default=0)),
                ("results_summary", models.JSONField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="HousingData",
        ),
    ]
