# Generated by Django 5.2.5 on 2025-09-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketanalysis", "0003_sale_upload_delete_housingdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
