# Generated by Django 5.2.5 on 2025-09-15 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketanalysis", "0004_upload_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="upload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="marketanalysis.upload",
            ),
        ),
    ]
