# Generated by Django 5.2.5 on 2025-09-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0003_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
