# Generated by Django 5.2.5 on 2025-09-09 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0004_contact_created_at_contact_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["-created_at"]},
        ),
    ]
