# Generated by Django 5.2.5 on 2025-09-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0005_alter_contact_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
